#3 added base back and mibrations
team-eight-brown/segmentaion-back pull request #4
Opened 2024-11-17 16:33 UTC by l1zail

Closes #3

2024-11-23 13:53 UTC, jakobiannn requested changes

2024-11-23 13:53 UTC, jakobiannn commented on src/main/java/com/vk/itmo/segmentation/dto/SegmentCreateRequest.java
> +public record SegmentCreateRequest(@NotNull @NotBlank String name, @NotNull @NotBlank String description) {
Спринг может в сериализацию рекордов?

2024-11-23 13:53 UTC, jakobiannn commented on src/main/resources/db/changelog/init-changelog.xml
> +            <column name="filter_expression" type="TEXT"/>
Мы будем проводить сегментацию по регекспу логинов, имеилов или ip, или проценту пользователей.
У нас не всегда будет user_percentage
Как вариант разбить эту таблицу на две (регекспы и распределения) или добавить сюда тип фильтра (email_regexp/ip_regexp/login_regexp/percent_distribution) получать BaseFilterEntity из jpa и парсить ее в необходимую модель в зависимости от type

2024-11-28 12:28 UTC, jakobiannn commented on .github/workflows/ci.yml
> +          docker push l1zail/segmentation:latest
Это будет происходить только при пуше в мастер?

2024-11-28 12:28 UTC, jakobiannn commented on .github/workflows/ci.yml
> +          POSTGRES_DB: test
С этим наверное что то не так

2024-11-28 16:40 UTC, l1zail commented on .github/workflows/ci.yml
> +          docker push l1zail/segmentation:latest
я тогда не поставила, чтобы проверить работает ли 
щас добавила

2024-11-29 07:55 UTC, jakobiannn approved these changes

2024-12-02 09:28 UTC, merged